/* =========================================================
STEP 11 : VALIDATION

Purpose
Verify that monitoring system is working correctly.

========================================================= */

SELECT COUNT(*) FROM AUTOMATE.EXP.VW_FAILED_QUERY_LOGS_24HR;
SELECT * FROM AUTOMATE.EXP.VW_FAILED_QUERY_LOGS_24HR;

SELECT COUNT(*) FROM AUTOMATE.EXP.VW_TOP_USERS_FAILED_QUERIES;
SELECT * FROM AUTOMATE.EXP.VW_TOP_USERS_FAILED_QUERIES;

SELECT COUNT(*) FROM AUTOMATE.EXP.VW_WAREHOUSE_CREDIT_USAGE;
SELECT * FROM AUTOMATE.EXP.VW_WAREHOUSE_CREDIT_USAGE;

SELECT COUNT(*) FROM AUTOMATE.EXP.VW_TOP_WAREHOUSE_CREDIT_USAGE;
SELECT * FROM AUTOMATE.EXP.VW_TOP_WAREHOUSE_CREDIT_USAGE;