/* =========================================================
STEP 6 : WAREHOUSE CREDIT MONITORING

Purpose
Track warehouse credit usage to identify high-cost
compute workloads.

Snowflake stores this information in

SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY

========================================================= */

CREATE OR REPLACE TABLE AUTOMATE.EXP.WAREHOUSE_USAGE_LOGS (

WAREHOUSE_NAME VARCHAR,
CREDITS_USED_COMPUTE NUMBER,
CREDITS_USED_CLOUD_SERVICES NUMBER,
CREDITS_USED NUMBER,
START_TIME TIMESTAMP,
END_TIME TIMESTAMP

);

INSERT INTO AUTOMATE.EXP.WAREHOUSE_USAGE_LOGS (

WAREHOUSE_NAME,
CREDITS_USED_COMPUTE,
CREDITS_USED_CLOUD_SERVICES,
CREDITS_USED,
START_TIME,
END_TIME

)

SELECT

WAREHOUSE_NAME,
CREDITS_USED_COMPUTE,
CREDITS_USED_CLOUD_SERVICES,
CREDITS_USED,
START_TIME,
END_TIME

FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;